### ISSUE TITLE
Vue.VueDragula not available

### ISSUE THREAD

**Issue by bhulsman** [Astray-git/vue-dragula#1]
In order to define Dragula options, I added a `created` function to my Vue instance. However, `Vue.VueDragula` is not available like shown in the docs.

So the example below does not work:

```
...
new Vue({
  ...
  created: function () {
    Vue.VueDragula.options('my-bag', {
      direction: 'vertical'
    })
  }
})
```

How can I configure dragula now?

**Comment by Astray-git** [comment]
Sorry, that's a mistake in doc. It should be `Vue.vueDragula.options`.

**Comment by bhulsman** [comment]
Thanks for the quick fix! That solves the problem indeed :+1:
