### ISSUE TITLE
copy: true behavior is buggy.

### ISSUE THREAD

**Issue by janwirth** [Astray-git/vue-dragula#10]
I encountered a bug when using `copy: true`. If you drop something, it will be created twice. 
I think this is because the model is changed and the gu-transit element is inserted as well. That's why we then have two occurences of the same object, while only one of them is linked to the model

demo:
http://46bb3f4c.ngrok.io/

If you point me in the right direction, that would be great and I will submit a PR. Thanks ahead.

**Comment by janwirth** [comment]
@nblackburn it did, in fact not remove the transit element inside the `cleanup` method. I created a hotfix.
See https://github.com/bevacqua/dragula/commit/d2091ab257d2d2e9b1fdcd73a38a9f3556816e17

You can install it with

``` sh
npm i --save-dev franzskuffka/dragula#d2091ab257d2d2e9b1fdcd73a38a9f3556816e17
```

**Comment by janwirth** [comment]
`removeOnSpill` does not work either.

```
Uncaught TypeError: Cannot read property 'removeChild' of null
```

**Comment by nblackburn** [comment]
@FranzSkuffka For the `removeOnSpill` error:

This is because Vue is trying to remove a node that has already been removed by Dragula. The fix was simply adding a check before attempting to delete the node from the DOM.
- **Issue**: https://github.com/vuejs/vue/issues/3302
- **PR**: https://github.com/vuejs/vue/pull/3303

Should this be merged, it will address the issue.

**Comment by nblackburn** [comment]
@FranzSkuffka Workaround for the duplicate drop error:

``` javascript
instance.on('drop', (element, target, origin) => {

    const isCopy = dragElement !== dropElement;

    if (isCopy && target.contains(element)) {
        element.remove();
    }
});
```

**Comment by Astray-git** [comment]
Thanks for the vue issue, we should let vue handle DOM update.
I cancelled dragula DOM actions.
