### ISSUE TITLE
Any way to get the new index I dragged to

### ISSUE THREAD

**Issue by varHarrie** [Astray-git/vue-dragula#13]
I am using `dropModel` event but there is no argument about the index.

I am trying to get the index like that:

``` javascript
Vue.vueDragula.eventBus.$on('dropModel', ([bag, el, target, source]) => {
  const index = Array.prototype.indexOf.call(target.children[i], el)
})
```

But the index always is -1, because the new element from target is not equal to the old element from source (More than 2 containers), it's a new object.

BTW, Is there any way to get the item from v-for array? Not the HTML element.

**Comment by varHarrie** [comment]
An unsatisfactory solution:

``` javascript
Vue.vueDragula.eventBus.$on('drop', ([bag, el, target, source, sibling]) => { // replace dropModel with drop event, and has 4 arguments
  let index = -1
  if (sibling) index = Array.prototype.indexOf.call(target.children, sibling) - 1
  else index = target.children.length - 1
})
```

Any better way?

**Comment by Astray-git** [comment]
`dropIndex` is exposed as a 5th element in dropModel callback args
