### ISSUE TITLE
Vue 2.0 support

### ISSUE THREAD

**Issue by magne4000** [Astray-git/vue-dragula#19]
Is there any plan on supporting new version 2.0 of Vue.js ?

**Comment by beeplin** [comment]
+1~

**Comment by amcsi** [comment]
I have created a PR to support ~~(only)~~ Vue 2.0
Here is the PR: #22

In the meantime you could use the vue2-build branch from my own fork as a temporary solution:
https://github.com/amcsi/vue-dragula/tree/vue2-build

EDIT: I have also updated my above vue2-build to also support both VueJS 1.0 and 2.0

**Comment by Astray-git** [comment]
1.3.0 released with #22

**Comment by amcsi** [comment]
@Astray-git when I used `npm build`, not just the minified js, but a non-minified dist js file was also built. But in your release commit you only added the minified js. Did you maybe forget to add the non-minified dist js?

**Comment by Astray-git** [comment]
https://github.com/Astray-git/vue-dragula/commit/1acafab0736f4d1d92ba935d6012b70588b1f4d5
You mean this one? There are 3 changed files.

**Comment by amcsi** [comment]
Oh silly me, i had that dist file there mixed up with the source file in my head. Never mind!

**Comment by amcsi** [comment]
@Astray-git It seems the latest version hasn't yet been published to npm. Is that normal?

**Comment by Astray-git** [comment]
@amcsi 😅 Sorry , I forgot to publish it.

**Comment by deiucanta** [comment]
I just tried this in Vue 2.0 and the list doesn't seem to order. I assume it conflicts with the virtual dom.

**Comment by amcsi** [comment]
@deiucanta please create a new issue for this
