### ISSUE TITLE
"require is not defined"

### ISSUE THREAD

**Issue by teckel12** [Astray-git/vue-dragula#23]
This script fails with an error:

```
var Vue = require('vue');
var VueDragula = require('vue-dragula');

Vue.use(VueDragula);
```

Therefore, can't get vue-dragula running.

**Comment by Astray-git** [comment]
Seems you are not using common js. You can directly include 'vue-dragula.js' with a `<script>` tag, It will automatically install itself.

**Comment by teckel12** [comment]
.

**Comment by teckel12** [comment]
I've rolled my own Vue/Dragula integration as I couldn't get vue-dragula.js to function with the latest release of Vue using nested drag and drop.
