### ISSUE TITLE
"dropModel" event not fired

### ISSUE THREAD

**Issue by jri** [Astray-git/vue-dragula#35]
I do:

    Vue.vueDragula.eventBus.$on("dropModel", ...)

But that event is never fired.

**Comment by Astray-git** [comment]
Can you tell me your vue-dragula version and vue version?

**Comment by jri** [comment]
vue-dragula 1.3.0 and vue 2.1.4

Meanwhile I see the "dropModel" event is fired sometimes, but I can't say when. I guess it is supposed to be fired along with the original "drop" event, but it isn't.

I thought the "dropModel" event would provide information about the underlying vue instance data. Meanwhile I found another way to get this data. Thanks.

**Comment by Astray-git** [comment]
you can try [2.0.0-alpha.1](https://github.com/Astray-git/vue-dragula/tree/next) for vue 2

**Comment by jri** [comment]
2.0.0-alpha.1 seems not yet be published at npm
https://www.npmjs.com/package/vue-dragula

I'am supposed to install it manually?

**Comment by jri** [comment]
Oh, sorry, now I see 2.0.0-alpha.1 IS available at npm.
I'll check it out now. Thank you.

**Comment by jri** [comment]
Using 2.0.0-alpha.1 the `drop-model` event is fired properly.
Thank you very much.
