### ISSUE TITLE
Issue with Mirror element

### ISSUE THREAD

**Issue by shortstuffsushi** [Astray-git/vue-dragula#44]
I'm new to both Vue and (Vue-)Dragula, so maybe I'm missing something obvious here. I've created a structure with container components that contain headers and then a list of draggable item components.

```
Vue.component('container', {
    props: [ 'group' ],
    data: function() {
        return {
            expanded: false
        }
    },
    methods: {
        onClick: function() {
            this.expanded = !this.expanded;
        }
    },
    template: '\
        <div class="group-container" @click="onClick"> \
            <div class="group-container-header">+ {{group.description}}</div> \
            <div class="group-container-rows" v-if="expanded" v-dragula="group.items" bag="items-bag"> \
                <row \
                    v-for="item in group.items" \
                    :item="item" \
                    :key="item.id" /> \
            </div> \
        </div>'
});
```

When I drag, I'm seeing the element I'm dragging end up at the bottom of the list outside of a container, which isn't desirable, but seems to be consistent with the dragula documentation mentioning the default behavior is `document.body`. I assume this is because I have something misconfigured... am I missing something in my simple example here?

Here's a runnable sample -- https://jsfiddle.net/shortstuffsushi/a8k941xm/

**Comment by Astray-git** [comment]
You can import `styles/dragula` to style mirror elements,

**Comment by shortstuffsushi** [comment]
Hmm, that seems to have fixed the issue in my jsfiddle, I'll have to give that a go in my real project tomorrow. I'll close this out, but reopen if it doesn't work for some reason. Thanks.

**Comment by shortstuffsushi** [comment]
Worked in my actual project as well. Thanks again. Maybe consider adding this to your "dist" folder so people who aren't using the npm / webpack version know they need to include it? Or in the docs?
