### ISSUE TITLE
Drake/Dragula API inaccessible

### ISSUE THREAD

**Issue by boris-glumpler** [Astray-git/vue-dragula#9]
Is there a way to access the Dragula API directly? I need to cancel a drop when certain conditions are met and can't find a way currently.

Thanks!

**Comment by Astray-git** [comment]
Normally, you can implement conditional drag&drop with [`moves`](https://github.com/bevacqua/dragula#optionsmoves) or [`accepts`](https://github.com/bevacqua/dragula#optionsaccepts) option methods.

For drake instances, I should expose the `find` method.

**Comment by boris-glumpler** [comment]
Ah, ok. I'll give that a try. Cheers!

**Comment by boris-glumpler** [comment]
Yup, worked perfectly!

**Comment by Alex-Sichkar** [comment]
So there is no way to access drake instance for now? I need to call drake .cancel() after unsuccessful AJAX request.

**Comment by Alex-Sichkar** [comment]
Thanks a lot!
